import { TestBed } from '@angular/core/testing';

import { ServiceGeneral } from './service-general';

describe('ServiceGeneral', () => {
  let service: ServiceGeneral;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(ServiceGeneral);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });

  it('setters should update their corresponding observables', () => {
    let changeComponent = '';
    let selectedPrompt = '';
    let selectedPromptImage = '';
    let selectedPromptBill = '';
    let responseMessagePrompt = '';
    let statusMessage = false;
    let isUploadingAnimation = false;
    let resizeInput = false;
    let imageBase64 = '';
    let executingImageStream = false;
    let executingBasicTemplateStream = false;
    let imageIds: any[] = [];
    let promptImages: any[] = [];
    let promptBills: any[] = [];
    let promptSystem: any[] = [];
    let promptData: any[] = [];
    let promptGlobalDefect: any[] = [];
    let syntheticData: any[] = [];
    let publicityData: any[] = [];
    let basicTemplateData: any[] = [];
    let toastMessage: any = undefined;
    let refreshPromptBills = '';
    let refreshPromptData = '';
    let refreshPromptImages = '';
    let refreshSyntheticData = '';
    let refreshPublicityData = '';
    let refreshBasicTemplate = '';
    let refreshPromptGlobalDefect = '';
    let refreshPromptSystem = '';
    let activateBasicTemplateStream = false;
    let activateUploadDocumentStream = false;
    let activateChatClientStream = false;
    let basicTemplate: any = {};
    let imageGenerated = '';
    let globalDefect: any[] = [];
    let chatClientStreamPrueba: any = {};

    service.changeComponent$.subscribe(v => changeComponent = v);
    service.selectedPrompt$.subscribe(v => selectedPrompt = v);
    service.selectedPromptImage$.subscribe(v => selectedPromptImage = v);
    service.selectedPromptBill$.subscribe(v => selectedPromptBill = v);
    service.responseMessagePrompt$.subscribe(v => responseMessagePrompt = v);
    service.statusMessage$.subscribe(v => statusMessage = v);
    service.isUploadingAnimation$.subscribe(v => isUploadingAnimation = v);
    service.resizeInput$.subscribe(v => resizeInput = v);
    service.imageBase64$.subscribe(v => imageBase64 = v);
    service.executingImageStream$.subscribe(v => executingImageStream = v);
    service.executingBasicTemplateStream$.subscribe(v => executingBasicTemplateStream = v);
    service.imageIds$.subscribe(v => imageIds = v);
    service.promptImages$.subscribe(v => promptImages = v);
    service.promptBills$.subscribe(v => promptBills = v);
    service.promptSystem$.subscribe(v => promptSystem = v);
    service.promptData$.subscribe(v => promptData = v);
    service.promptGlobalDefect$.subscribe(v => promptGlobalDefect = v);
    service.syntheticData$.subscribe(v => syntheticData = v);
    service.publicityData$.subscribe(v => publicityData = v);
    service.basicTemplateData$.subscribe(v => basicTemplateData = v);
    service.toastMessage$.subscribe(v => toastMessage = v);
    service.refreshPromptBills$.subscribe(v => refreshPromptBills = v);
    service.refreshPromptData$.subscribe(v => refreshPromptData = v);
    service.refreshPromptImages$.subscribe(v => refreshPromptImages = v);
    service.refreshSyntheticData$.subscribe(v => refreshSyntheticData = v);
    service.refreshPublicityData$.subscribe(v => refreshPublicityData = v);
    service.refreshBasicTemplate$.subscribe(v => refreshBasicTemplate = v);
    service.refreshPromptGlobalDefect$.subscribe(v => refreshPromptGlobalDefect = v);
    service.refreshPromptSystem$.subscribe(v => refreshPromptSystem = v);
    service.activateBasicTemplateStream$.subscribe(v => activateBasicTemplateStream = v);
    service.activateUploadDocumentStream$.subscribe(v => activateUploadDocumentStream = v);
    service.activateChatClientStream$.subscribe(v => activateChatClientStream = v);
    service.basicTemplate$.subscribe(v => basicTemplate = v);
    service.imageGenerated$.subscribe(v => imageGenerated = v);
    service.globalDefect$.subscribe(v => globalDefect = v);
    service.chatClientStreamPrueba$.subscribe(v => chatClientStreamPrueba = v);

    service.setChangeComponent('comp');
    service.setSelectedPrompt('p');
    service.setSelectedPromptImage('pi');
    service.setSelectedPromptBill('pb');
    service.setResponseMessagePrompt('rm');
    service.setStatusMessage(true);
    service.setIsUploadingAnimation(true);
    service.setResizeInput(true);
    service.setImageBase64('img');
    service.setExecutingImageStream(true);
    service.setExecutingBasicTemplatStream(true);
    service.setImageIds([1]);
    service.setPromptImages([2] as any);
    service.setPromptBills([3] as any);
    service.setPromptSystem([4] as any);
    service.setPromptData([5] as any);
    service.setPromptGlobalDefect([6] as any);
    service.setGlobalDefect([7] as any);
    service.setSyntheticData([8] as any);
    service.setPublicityData([9] as any);
    service.setBasicTemplateData([10] as any);
    service.setToastMessage({ severity: 'success' } as any);
    service.setRefreshPromptBills('rb');
    service.setRefreshPromptData('rd');
    service.setRefreshPromptImages('ri');
    service.setRefreshSyntheticData('rs');
    service.setRefreshPublicityData('rpu');
    service.setRefreshBasicTemplate('rbt');
    service.setRefreshPromptGlobalDefect('rpgd');
    service.setRefreshPromptSystem('rps');
    service.setActivateBasicTemplateStream(true);
    service.setActivateUploadDocumentStream(true);
    service.setActivateChatClientStream(true);
    service.setBasicTemplate({ id: 1 });
    service.setImageGenerated('gen');
    service.setActivateChatClientStreamPrueba({ prompt: 'x' } as any);

    expect(changeComponent).toBe('comp');
    expect(selectedPrompt).toBe('p');
    expect(selectedPromptImage).toBe('pi');
    expect(selectedPromptBill).toBe('pb');
    expect(responseMessagePrompt).toBe('rm');
    expect(statusMessage).toBeTrue();
    expect(isUploadingAnimation).toBeTrue();
    expect(resizeInput).toBeTrue();
    expect(imageBase64).toBe('img');
    expect(executingImageStream).toBeTrue();
    expect(executingBasicTemplateStream).toBeTrue();
    expect(imageIds).toEqual([1]);
    expect(promptImages).toEqual([2] as any);
    expect(promptBills).toEqual([3] as any);
    expect(promptSystem).toEqual([4] as any);
    expect(promptData).toEqual([5] as any);
    expect(promptGlobalDefect).toEqual([6] as any);
    expect(globalDefect).toEqual([7] as any);
    expect(syntheticData).toEqual([8] as any);
    expect(publicityData).toEqual([9] as any);
    expect(basicTemplateData).toEqual([10] as any);
    expect(toastMessage).toEqual({ severity: 'success' } as any);
    expect(refreshPromptBills).toBe('rb');
    expect(refreshPromptData).toBe('rd');
    expect(refreshPromptImages).toBe('ri');
    expect(refreshSyntheticData).toBe('rs');
    expect(refreshPublicityData).toBe('rpu');
    expect(refreshBasicTemplate).toBe('rbt');
    expect(refreshPromptGlobalDefect).toBe('rpgd');
    expect(refreshPromptSystem).toBe('rps');
    expect(activateBasicTemplateStream).toBeTrue();
    expect(activateUploadDocumentStream).toBeTrue();
    expect(activateChatClientStream).toBeTrue();
    expect(basicTemplate).toEqual({ id: 1 } as any);
    expect(imageGenerated).toBe('gen');
    expect(chatClientStreamPrueba).toEqual({ prompt: 'x' } as any);
  });
});
